---
title: "Plot estimates of pi0"
author: "Matthew Stephens"
date: 2015-10-26
---

**Last updated:** `r Sys.Date()`

**Code version:** `r system("git log -1 --format='%H'", intern = TRUE)`

First, we load the necessary libraries, and specify settings for
displaying the plots in the rendered document.

```{r chunk_options, include=FALSE}
library(magrittr)
library(dplyr)
source("chunk-options.R")
source("../R/set_plot_colors.R")
```

Generate scatterplots compare the estimated estimate of pi0 against the 
ground-truth value, colored by the method used, and split by the scenario
type.

```{r plot_pi0est, dev='pdf', crop=TRUE}
load("../output/dsc-shrink-files/res.RData")

PLOTMETHODS   = c("mixfdr.tnull","ash.n","ash.u","qvalue","locfdr")
PLOTSCENARIOS = c("spiky","near-normal","flat-top","skew","bimodal")
PLOTNAMES     = PLOTSCENARIOS
ALPHALEVEL    = 0.8 # controls transparency

df = res$pi0_score %>% 
       filter(scenario %in% PLOTSCENARIOS) %>% 
       filter(method %in% PLOTMETHODS)
df$scenario = factor(df$scenario,levels=PLOTSCENARIOS)
levels(df$scenario) = PLOTNAMES

pi0_plot = ggplot(df,aes(pi0,pi0_est,colour = method,alpha = ALPHALEVEL)) +
  geom_point(shape = 1) +
  facet_grid(. ~ scenario) + 
  guides(alpha = FALSE) +
  geom_abline(colour = "black") +
  xlab("True pi0") +
  ylab("Estimated pi0") 
print(pi0_plot + scale_y_continuous(limits = c(0,1.01)) +
        scale_x_continuous(limits = c(0,1.01)) +
        coord_equal(ratio = 1) + 
        colScale + 
        theme(legend.position = "top",
              axis.text.x     = element_text(size = 8,angle = 45)))
```

## Session information

```{r info}
sessionInfo()
```
