---
title: "Various examples of cdf plots"
author: "Matthew Stephens"
date: 2015-10-26
---

**Last updated:** `r Sys.Date()`

**Code version:** `r system("git log -1 --format='%H'", intern = TRUE)`

First, we load the necessary libraries, and specify settings for
displaying the plots in the rendered document.

```{r chunk_options, include=FALSE}
library(plyr)
library(dplyr)
library(magrittr)
library(ashr)
library(ggplot2)
library(dscr)
source("chunk-options.R")
source("../code/dsc-shrink/methods/mixfdr.wrapper.R")
source("../R/set_plot_colors.R")
```

*Explain here what this chunk does.*

```{r chunk_label}
load("../output/dsc-shrink-files/res.RData")

#df is a list with components method,seed, scenario
#cdf is evaluated at x
#returns list of x,y,pi0, where cdf values are in y
get_cdf = function(df,dsc=dsc_shrink,x=seq(-6,6,length=100),homedir="../code/dsc-shrink"){
  m=df$method
  if(m=="truth"){m="ash.n"}
  temp=load_example(dsc,df$seed,df$scenario,m,homedir)
  pi0=temp$meta$pi0
  
  if(df$method=="truth"){
    s=dsc$scenarios[[df$scenario]]
    galt=s$args$g
    g=normalmix(c(pi0,(1-pi0)*mixprop(galt)),
                c(0,comp_mean(galt)),
                c(0,comp_sd(galt)))
  } else {
    if(grepl("mixfdr",df$method)){
      temp$output= mixfdr2fitted.g(temp$output)
    }
    g=temp$output$fitted.g
  }
  data.frame(x=x,y=as.numeric(mixcdf(g,x)),pi0=pi0)
}

plot_mean_cdf = function(SEEDS,PLOTMETHODS=c("ash.n","ash.u","ash.hu","truth","mixfdr.tnull"),
      PLOTSCENARIOS=c("spiky","near-normal","flat-top","skew","bimodal"),pi0filter=FALSE,...){
  PLOTNAMES = PLOTSCENARIOS
  #set up dataframe with cdf for all methods and all datasets
  df= expand.grid(seed=SEEDS,scenario=PLOTSCENARIOS, method=PLOTMETHODS,stringsAsFactors = FALSE)
  df.cdf=ddply(df,.(seed,scenario,method), get_cdf)
  
  if(pi0filter==TRUE){
    df.cdf %<>% filter(pi0<0.55 & pi0>0.45)
  }
  if(length(SEEDS)>1){
    df.cdf %<>% group_by(x,method,scenario) %>% dplyr::summarise(y=mean(y))
  }
  
  df.cdf$scenario=factor(df.cdf$scenario,levels=PLOTSCENARIOS)
  levels(df.cdf$scenario)=PLOTNAMES

  ggplot(df.cdf,aes(x=x,y=y,color=method),...) + colScale + geom_line(lwd=1.5,alpha=0.7) + facet_grid(.~scenario) + theme(legend.position = "bottom")

}
```

```{r egcdf, dev='pdf',fig.height=3, fig.width=9, crop=TRUE}
plot_mean_cdf(1)
```

```{r mean_cdf, dev='pdf',fig.height=3, fig.width=9, crop=TRUE}
plot_mean_cdf(1:100,PLOTMETHODS=c("ash.n","ash.u","ash.hu","truth"),pi0filter=TRUE)
```

```{r mean_cdf_nopen, dev='pdf',fig.height=3, fig.width=9, crop=TRUE}
names(myColors) <- c("truth","ash.hu.s","ash.n.s","ash.u.s","qvalue","locfdr","mixfdr.tnull")
colScale <- scale_colour_manual(name = "method",values = myColors)
plot_mean_cdf(1:100,PLOTMETHODS=c("ash.n.s","ash.u.s","ash.hu.s","truth"),pi0filter=TRUE)
source("../R/set_plot_colors.R") #reset color scale for other plots
```

The following plots have fewer methods and scenarios for more clarity

```{r egcdf-reduce, dev='pdf',fig.height=3, fig.width=6, crop=TRUE}
plot_mean_cdf(1,PLOTMETHODS=c("ash.n","truth"),PLOTSCENARIOS = c("spiky","near-normal","bimodal"))
```

```{r mean_cdf-reduce, dev='pdf',fig.height=3, fig.width=6, crop=TRUE}
plot_mean_cdf(1:100,PLOTMETHODS=c("ash.n","truth"),PLOTSCENARIOS = c("spiky","near-normal","bimodal"),pi0filter=TRUE)
```

```{r mean_cdf_nopen-reduce, dev='pdf',fig.height=3, fig.width=6, crop=TRUE}
names(myColors) <- c("truth","ash.hu.s","ash.n.s","ash.u.s","qvalue","locfdr","mixfdr.tnull")
colScale <- scale_colour_manual(name = "method",values = myColors)
plot_mean_cdf(1:100,PLOTMETHODS=c("ash.n.s","truth"),PLOTSCENARIOS = c("spiky","near-normal","bimodal"), pi0filter=TRUE)
source("../R/set_plot_colors.R")
```

I wanted to add the npmle to the plot...

```{r egcdf-reduce-with-npmle, dev='pdf',fig.height=4.5, fig.width=6, crop=TRUE}
run_nplme=function(SEED=1,PLOTSCENARIOS=c("spiky","near-normal","flat-top","skew","big-normal","bimodal")){
  df=data.frame(seed=NULL,scenario=NULL,method=NULL,x=NULL,y=NULL,pi0=NULL)
  for(SCENARIO in PLOTSCENARIOS){
    temp=dscr::load_example(dsc_shrink,SEED,SCENARIO,"ash.n","../output/dsc-shrink-files/")
    z <- REBayes::GLmix(temp$input$betahat)
    df = rbind(df,data.frame(seed=SEED,scenario=SCENARIO,method="NPMLE",x=z$x,y=cumsum(z$y)/sum(z$y),pi0=NA))
  }
  return(df)
}


plot_mean_cdf_with_npmle = function(SEED=1,PLOTMETHODS=c("ash.n","ash.u","ash.hu","truth","mixfdr.tnull"),
      PLOTSCENARIOS=c("spiky","near-normal","flat-top","skew","big-normal","bimodal"),pi0filter=FALSE,...){
  if(length(SEED)>1){stop("plot with npmle only implemented for a single seed")}
  PLOTNAMES=PLOTSCENARIOS
  #set up dataframe with cdf for all methods and all datasets
  df= expand.grid(seed=SEED,scenario=PLOTSCENARIOS, method=PLOTMETHODS,stringsAsFactors = FALSE)
  df.cdf=plyr::ddply(df,.(seed,scenario,method), get_cdf)
  
  
  df.cdf$scenario=factor(df.cdf$scenario,levels=PLOTSCENARIOS)
  levels(df.cdf$scenario)=PLOTNAMES
  
  df.npmle = run_nplme(SEED, PLOTSCENARIOS)
  df.cdf = rbind(df.cdf,df.npmle)
  
  p=ggplot(df.cdf,aes(x=x,y=y,color=method),...) +  xlim(c(-4,4)) + colScale + geom_line(lwd=1.2,alpha=0.7)  + theme(legend.position = "bottom")
  return(p)
}

plot_mean_cdf_with_npmle(1,PLOTMETHODS=c("truth","ash.hu"),PLOTSCENARIOS = c("spiky","near-normal","flat-top","skew","big-normal","bimodal")) + facet_wrap(~ scenario, nrow=2)
```

## Session information

```{r info}
sessionInfo()
```
